# curso de desenvolvimento de sistemas
# turma 0152 (braba)
# autor:Beatriz Victoria
# data: 21/05/2024
# Faça um programa que leia o nome de um aluno e mostre quantas vezes a letra 'o' aparece e em que posição ela aparece pela primeira e última vez.


import os

os.system('cls')

print('='*70)
print('nome do aluno')
print('-'*70)

# entrando com o nome
print('-'*70)
nome = str(input('nome do aluno: '))
print('-'*70)

# processamento
nome_minusculo = nome.lower()
numero_o = nome_minusculo.count('o')
print(f'A letra O aparece {numero_o} vezes na frase')
print('A primeira a letra O aparece na pocicao {}'.find(frase.upper('o'))
print('A ultima palavra letra o aparece opocicao {}'.find(frase.upper('o'))
      
nome_minusculo = nome
numero_o = nome

print('o aparece:' {nome_minusculo})
print('aparece na primeira posicao: {primeira} ')
print('aparece na ultima posicao:  {ultima}' )