# curso de deselvolvimento de sistemas
# turma 0152
# data: 09/05/2024
# nome: Beatriz Victoria
# atividade 003-funcoes/metodos internos
# Faça um programa onde o usuário tenta adivinhar o número que o computador está ‘pensando’.

import random
import os


os.system('cls')

print('-'*70)
print('biblioteca random')
print('='*70 )

print('numero aleatorio')
numero_aleatorio = random.random
'o numero aleatorio gerado foi:'  {aleatorio}